# Generated by Django 5.2.7 on 2025-10-05 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genero_libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('version', models.IntegerField()),
                ('color_portada', models.CharField(max_length=20)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genero_libro.genero_libro')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
