# Generated by Django 5.2.7 on 2025-10-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genero_libro', '0001_initial'),
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='genero_libro.genero_libro'),
        ),
    ]
