# Generated by Django 5.2.7 on 2025-10-08 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_alter_libro_genero'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuario.usuario'),
            preserve_default=False,
        ),
    ]
