# Generated by Django 5.2.7 on 2025-10-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_libro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='libros/portadas'),
        ),
    ]
