# Generated by Django 5.2.7 on 2025-10-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_libro_imagen_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='color_portada',
            field=models.CharField(default='sin color', max_length=20),
        ),
    ]
