# Generated by Django 5.2.7 on 2025-10-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_alter_libro_color_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='es_publico',
            field=models.BooleanField(default=True),
        ),
    ]
