# Generated by Django 5.2.7 on 2025-10-12 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0006_libro_es_publico'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('es_favorito', models.BooleanField(default=False)),
                ('ultima_pagina_leida', models.IntegerField(default=0)),
                ('pendiente_leer', models.BooleanField(default=False)),
                ('calificacion', models.IntegerField(default=0)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
