# Generated by Django 5.2.7 on 2025-10-12 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones_usuario', '0001_initial'),
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones_usuario',
            name='ultima_pagina_leida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_usuario', to='pagina.pagina'),
        ),
    ]
